[package]
name = "icedoku"
version = "0.1.0"
edition = "2024"

[features]
debug = ["iced/debug"]

[dependencies]
iced = "0.14"

[lints.rust]
unsafe_code = "warn"
deprecated = "warn"
missing_debug_implementations = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }

pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"

cargo = { level = "warn", priority = -1 }
cargo_common_metadata = "allow"
multiple_crate_versions = "allow"

unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
print_stdout = "warn"
wildcard_imports = "warn"
absolute_paths = "warn"
same_name_method = "warn"
